# Generated by Django 4.2.9 on 2026-02-25 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='tutorial_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
