# Generated by Django 4.2.9 on 2026-03-05 00:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0003_workoutprogram_workoutsplit_workoutprogramexercise_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkoutLog",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("exercise", models.CharField(max_length=120)),
                ("sets", models.PositiveIntegerField(default=1)),
                ("reps", models.PositiveIntegerField(default=0)),
                ("weight", models.DecimalField(decimal_places=2, default=0, max_digits=7)),
                ("date", models.DateField(default=django.utils.timezone.now)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="workout_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "-created_at", "-id"],
            },
        ),
    ]
