# Generated by Django 4.2.9 on 2026-03-15 08:58

import base.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_refactor_exercise_library'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='exercise',
            new_name='base_exerci_categor_df0d6b_idx',
            old_name='base_exerci_categor_7a8c2a_idx',
        ),
        migrations.AlterField(
            model_name='exercise',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='equipment_needed',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='video_url',
            field=models.URLField(validators=[base.validators.validate_youtube_url]),
        ),
    ]
