# Generated by Django 6.0.3 on 2026-03-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_userprofile_free_chat_messages_used_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='free_chat_usage_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
